In [1]:
from bs4 import BeautifulSoup
import requests

In [ ]:
#url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
#page =requests.get(url)
#Soup = BeautifulSoup(page.text, 'html')

#print(Soup)

Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.

In [62]:

headers = {
    "User-Agent": "MyDataScienceBot/1.0 (your_email@example.com)"
}

url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
response = requests.get(url, headers=headers)

#print(response.status_code)
Soup = BeautifulSoup(page.text,'html')
print(Soup)

Please set a user-agent and respect our robot policy https://w.wiki/4wJS. See also https://phabricator.wikimedia.org/T400119.

In [9]:
pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 390.1 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/4.0 MB 390.1 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/4.0 MB 390.1 kB/s eta 0:00:09
   ------- -------------------------------- 0.8/4.0 MB 459.5 kB/s eta 0:00:08
   ------- -------------------------------- 0.8/4.0 MB 459.5 kB/s eta 0:00:08
   ---------- ----------------------------- 1.0/4.0 MB 479.2 kB/s eta 0:00:07
   ---------- ----------------------------- 1.0/4.0 MB 479.2 kB/s eta 0:00:07
   ------------- -------------------------- 1.3/4.0 MB 500.8 kB/s eta 0:00:06
   ------------- -------------------------- 1.3/4.0 MB 500.8 kB/s eta 0:00:06
   --------------- ------------------------ 1.6/4.0 MB 514.6 kB/s eta 0:00:05
   --------------- ------------------------ 1.6/4.0 MB 514.6 kB/s eta 0:00:05
   --------------- ------------------------ 1.6/4.0 MB 514.6 kB/s eta 0:00:05
   --------------- ------------------------ 1.6/4.0 MB 514.6 kB/s eta 0:00:05
   ------------------ --------------------- 1.8/4.0 MB 463.8 kB/s eta 0:00:05
   ------------------ --------------------- 1.8/4.0 MB 463.8 kB/s eta 0:00:05
   ------------------ --------------------- 1.8/4.0 MB 463.8 kB/s eta 0:00:05
   ------------------ --------------------- 1.8/4.0 MB 463.8 kB/s eta 0:00:05
   -------------------- ------------------- 2.1/4.0 MB 431.8 kB/s eta 0:00:05
   -------------------- ------------------- 2.1/4.0 MB 431.8 kB/s eta 0:00:05
   -------------------- ------------------- 2.1/4.0 MB 431.8 kB/s eta 0:00:05
   -------------------- ------------------- 2.1/4.0 MB 431.8 kB/s eta 0:00:05
   ----------------------- ---------------- 2.4/4.0 MB 418.1 kB/s eta 0:00:04
   ----------------------- ---------------- 2.4/4.0 MB 418.1 kB/s eta 0:00:04
   ----------------------- ---------------- 2.4/4.0 MB 418.1 kB/s eta 0:00:04
   ----------------------- ---------------- 2.4/4.0 MB 418.1 kB/s eta 0:00:04
   ----------------------- ---------------- 2.4/4.0 MB 418.1 kB/s eta 0:00:04
   -------------------------- ------------- 2.6/4.0 MB 387.1 kB/s eta 0:00:04
   -------------------------- ------------- 2.6/4.0 MB 387.1 kB/s eta 0:00:04
   -------------------------- ------------- 2.6/4.0 MB 387.1 kB/s eta 0:00:04
   -------------------------- ------------- 2.6/4.0 MB 387.1 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 370.4 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 370.4 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 370.4 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 370.4 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 370.4 kB/s eta 0:00:04
   ------------------------------- -------- 3.1/4.0 MB 355.6 kB/s eta 0:00:03
   ------------------------------- -------- 3.1/4.0 MB 355.6 kB/s eta 0:00:03
   ------------------------------- -------- 3.1/4.0 MB 355.6 kB/s eta 0:00:03
   ------------------------------- -------- 3.1/4.0 MB 355.6 kB/s eta 0:00:03
   ------------------------------- -------- 3.1/4.0 MB 355.6 kB/s eta 0:00:03
   --------------------------------- ------ 3.4/4.0 MB 343.6 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 343.6 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 343.6 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 343.6 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 343.6 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 332.5 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 332.5 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 332.5 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 332.5 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 332.5 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 332.5 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 332.5 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 332.5 kB/s eta 0:00:02
   ---------------------------------------  3.9/4.0 MB 307.4 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 307.4 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 307.4 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 307.4 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 307.4 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 307.4 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 284.3 kB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
pip install lxml --upgrade

Requirement already satisfied: lxml in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (6.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
pip install lxml

Requirement already satisfied: lxml in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (6.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import sys
print(sys.executable)

c:\Users\PC\AppData\Local\Programs\Python\Python312\python.exe

In [20]:
!{sys.executable} -m pip install lxml html5lib beautifulsoup4

Requirement already satisfied: lxml in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (6.0.2)
Requirement already satisfied: html5lib in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (4.14.3)
Requirement already satisfied: six>=1.9 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4) (4.15.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [81]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

headers = {
    "User-Agent": "MyDataScienceBot/1.0 (timothykabira@gmail.com)"
}

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

table = soup.find("table", {"class": "wikitable"})

rows = table.find_all("tr")

data = []
for row in rows:
    cols = row.find_all(["td", "th"])
    cols = [col.text.strip() for col in cols]
    data.append(cols)

df = pd.DataFrame(data[1:], columns=data[0])

print(df.head())

  Rank                Name                    Industry Revenue (USD millions)  \
0    1             Walmart                      Retail                680,985
1    2              Amazon  Retail and cloud computing                637,959
2    3  UnitedHealth Group                  Healthcare                400,278
3    4               Apple                  Technology                391,035
4    5          CVS Health                  Healthcare                372,809

  Revenue growth  Employees              Headquarters
0           5.1%  2,100,000     Bentonville, Arkansas
1          11.0%  1,556,000       Seattle, Washington
2           7.7%    400,000     Minnetonka, Minnesota
3           2.0%    164,000     Cupertino, California
4           4.2%    259,500  Woonsocket, Rhode Island

In [114]:
#table = soup.find_all("table", {"class": "wikitable"})
table=soup.find_all('table')
print(table)

[<table class="wikitable sortable">
<caption>
</caption>
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue <br/>(USD millions)
</th>
<th>Revenue growth
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">680,985
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.1%
</td>
<td style="text-align:center;">2,100,000
</td>
<td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
</td>
<td>Retail and cloud computing
</td>
<td style="text-align:center;">637,959
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.0%
</td>
<td style="text-align:center;">1,556,000
</td>
<td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
</td></tr>
<tr>
<td>3
</td>
<td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">400,278
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 7.7%
</td>
<td style="text-align:center;">400,000
</td>
<td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
</td></tr>
<tr>
<td>4
</td>
<td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
</td>
<td>Technology
</td>
<td style="text-align:center;">391,035
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 2.0%
</td>
<td style="text-align:center;">164,000
</td>
<td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">372,809
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.2%
</td>
<td style="text-align:center;">259,500
</td>
<td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">371,433
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.9%
</td>
<td style="text-align:center;">392,400
</td>
<td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
</td></tr>
<tr>
<td>7
</td>
<td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">350,018
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.9%
</td>
<td style="text-align:center;">183,323
</td>
<td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/ExxonMobil" title="ExxonMobil">Exxon Mobil</a>
</td>
<td>Petroleum
</td>
<td style="text-align:center;">349,595
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.5%
</td>
<td style="text-align:center;">60,900
</td>
<td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">308,951
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.7%
</td>
<td style="text-align:center;">48,000
</td>
<td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
</td>
<td>Pharmacy wholesale
</td>
<td style="text-align:center;">293,959
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 12.1%
</td>
<td style="text-align:center;">44,000
</td>
<td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">278,906
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 16.5%
</td>
<td style="text-align:center;">317,233
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Costco" title="Costco">Costco Wholesale</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">254,453
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
</td>
<td style="text-align:center;">333,000
</td>
<td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
</td></tr>
<tr>
<td>13
</td>
<td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
</td>
<td>Health insurance
</td>
<td style="text-align:center;">247,121
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 26.6%
</td>
<td style="text-align:center;">72,398
</td>
<td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
</td></tr>
<tr>
<td>14
</td>
<td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">245,122
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 15.7%
</td>
<td style="text-align:center;">228,000
</td>
<td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">226,827
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.6%
</td>
<td style="text-align:center;">48,411
</td>
<td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron</a>
</td>
<td>Petroleum
</td>
<td style="text-align:center;">202,792
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 0.9%
</td>
<td style="text-align:center;">45,298
</td>
<td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">192,434
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
</td>
<td style="text-align:center;">213,193
</td>
<td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
</td>
<td>Automotive
</td>
<td style="text-align:center;">187,442
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.1%
</td>
<td style="text-align:center;">162,000
</td>
<td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor</a>
</td>
<td>Automotive
</td>
<td style="text-align:center;">184,992
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
</td>
<td style="text-align:center;">171,000
</td>
<td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
</td></tr>
<tr>
<td>20
</td>
<td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">177,011
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 3.3%
</td>
<td style="text-align:center;">103,679
</td>
<td><a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">170,757
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 8.9%
</td>
<td style="text-align:center;">227,855
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>22
</td>
<td><a href="/wiki/Meta_Platforms" title="Meta Platforms">Meta Platforms</a>
</td>
<td>Technology
</td>
<td style="text-align:center;">164,501
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 21.9%
</td>
<td style="text-align:center;">74,067
</td>
<td><a href="/wiki/Menlo_Park,_California" title="Menlo Park, California">Menlo Park, California</a>
</td></tr>
<tr>
<td>23
</td>
<td><a class="mw-redirect" href="/wiki/Centene" title="Centene">Centene</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">163,071
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.9%
</td>
<td style="text-align:center;">60,500
</td>
<td><a href="/wiki/St._Louis" title="St. Louis">St. Louis, Missouri</a>
</td></tr>
<tr>
<td>24
</td>
<td><a class="mw-redirect" href="/wiki/The_Home_Depot" title="The Home Depot">The Home Depot</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">159,514
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.5%
</td>
<td style="text-align:center;">470,100
</td>
<td><a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>
</td></tr>
<tr>
<td>25
</td>
<td><a href="/wiki/Fannie_Mae" title="Fannie Mae">Fannie Mae</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">152,670
</td>

In [117]:
table = soup.find('table', {'class': 'wikitable'})

world_titles = [th.text.strip() for th in table.find_all('th')]

print(world_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [119]:
#world_table_titles=[title.text for title in world_titles]
#print(world_table_titles)

In [120]:
#world_table_titles=[title.text.strip() for title in world_titles]
#print(world_table_titles)

In [121]:
#table = soup.find_all("table", {"class": "wikitable"})[1]
#print(table)

In [118]:
#Soup.find('table',class ='wikitable sortable')

#table = soup.find("table", class_="wikitable sortable")
#print(table)

In [123]:
#table = Soup.find_all('table')[1]

#tables = soup.find_all("table")
#print(len(tables))   # see how many tables BeautifulSoup actually found

In [122]:
#print(response.status_code)    # should be 200
#print(response.text[:500])     # preview first 500 characters

In [124]:
# Find all headers
headers_list = soup.find_all('th')
for h in headers_list[:]:  # preview first 10
    print(h.text.strip())

Rank
Name
Industry
Revenue (USD millions)
Revenue growth
Employees
Headquarters
Rank
Name
Industry
Revenue (USD billions)
Employees
Headquarters
Rank
Name
Industry
Profits(USD millions)
Headquarters

In [125]:
df=pd.DataFrame(columns = world_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [126]:
table.find_all('tr')

[<tr>
 <th>Rank
 </th>
 <th>Name
 </th>
 <th>Industry
 </th>
 <th>Revenue <br/>(USD millions)
 </th>
 <th>Revenue growth
 </th>
 <th>Employees
 </th>
 <th>Headquarters
 </th></tr>,
 <tr>
 <td>1
 </td>
 <td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">680,985
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.1%
 </td>
 <td style="text-align:center;">2,100,000
 </td>
 <td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
 </td></tr>,
 <tr>
 <td>2
 </td>
 <td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
 </td>
 <td>Retail and cloud computing
 </td>
 <td style="text-align:center;">637,959
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.0%
 </td>
 <td style="text-align:center;">1,556,000
 </td>
 <td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
 </td></tr>,
 <tr>
 <td>3
 </td>
 <td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">400,278
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 7.7%
 </td>
 <td style="text-align:center;">400,000
 </td>
 <td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
 </td></tr>,
 <tr>
 <td>4
 </td>
 <td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
 </td>
 <td>Technology
 </td>
 <td style="text-align:center;">391,035
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 2.0%
 </td>
 <td style="text-align:center;">164,000
 </td>
 <td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
 </td></tr>,
 <tr>
 <td>5
 </td>
 <td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">372,809
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.2%
 </td>
 <td style="text-align:center;">259,500
 </td>
 <td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
 </td></tr>,
 <tr>
 <td>6
 </td>
 <td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
 </td>
 <td>Conglomerate
 </td>
 <td style="text-align:center;">371,433
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.9%
 </td>
 <td style="text-align:center;">392,400
 </td>
 <td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
 </td></tr>,
 <tr>
 <td>7
 </td>
 <td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
 </td>
 <td>Technology and cloud computing
 </td>
 <td style="text-align:center;">350,018
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.9%
 </td>
 <td style="text-align:center;">183,323
 </td>
 <td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
 </td></tr>,
 <tr>
 <td>8
 </td>
 <td><a href="/wiki/ExxonMobil" title="ExxonMobil">Exxon Mobil</a>
 </td>
 <td>Petroleum
 </td>
 <td style="text-align:center;">349,595
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.5%
 </td>
 <td style="text-align:center;">60,900
 </td>
 <td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
 </td></tr>,
 <tr>
 <td>9
 </td>
 <td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">308,951
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.7%
 </td>
 <td style="text-align:center;">48,000
 </td>
 <td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
 </td></tr>,
 <tr>
 <td>10
 </td>
 <td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
 </td>
 <td>Pharmacy wholesale
 </td>
 <td style="text-align:center;">293,959
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 12.1%
 </td>
 <td style="text-align:center;">44,000
 </td>
 <td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
 </td></tr>,
 <tr>
 <td>11
 </td>
 <td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">278,906
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 16.5%
 </td>
 <td style="text-align:center;">317,233
 </td>
 <td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
 </td></tr>,
 <tr>
 <td>12
 </td>
 <td><a href="/wiki/Costco" title="Costco">Costco Wholesale</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">254,453
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
 </td>
 <td style="text-align:center;">333,000
 </td>
 <td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
 </td></tr>,
 <tr>
 <td>13
 </td>
 <td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
 </td>
 <td>Health insurance
 </td>
 <td style="text-align:center;">247,121
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 26.6%
 </td>
 <td style="text-align:center;">72,398
 </td>
 <td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
 </td></tr>,
 <tr>
 <td>14
 </td>
 <td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
 </td>
 <td>Technology and cloud computing
 </td>
 <td style="text-align:center;">245,122
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 15.7%
 </td>
 <td style="text-align:center;">228,000
 </td>
 <td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
 </td></tr>,
 <tr>
 <td>15
 </td>
 <td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">226,827
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.6%
 </td>
 <td style="text-align:center;">48,411
 </td>
 <td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
 </td></tr>,
 <tr>
 <td>16
 </td>
 <td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron</a>
 </td>
 <td>Petroleum
 </td>
 <td style="text-align:center;">202,792
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 0.9%
 </td>
 <td style="text-align:center;">45,298
 </td>
 <td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
 </td></tr>,
 <tr>
 <td>17
 </td>
 <td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">192,434
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
 </td>
 <td style="text-align:center;">213,193
 </td>
 <td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
 </td></tr>,
 <tr>
 <td>18
 </td>
 <td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
 </td>
 <td>Automotive
 </td>
 <td style="text-align:center;">187,442
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.1%
 </td>
 <td style="text-align:center;">162,000
 </td>
 <td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
 </td></tr>,
 <tr>
 <td>19
 </td>
 <td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor</a>
 </td>
 <td>Automotive
 </td>
 <td style="text-align:center;">184,992
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
 </td>
 <td style="text-align:center;">171,000
 </td>
 <td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
 </td></tr>,
 <tr>
 <td>20
 </td>
 <td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">177,011
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 3.3%
 </td>
 <td style="text-align:center;">103,679
 </td>
 <td><a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>
 </td></tr>,
 <tr>
 <td>21
 </td>
 <td><a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>
 </td>
 <td>Financials
 </td>
 <td style="text-align:center;">170,757
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 8.9%
 </td>
 <td style="text-align:center;">227,855
 </td>
 <td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
 </td></tr>,
 <tr>
 <td>22
 </td>
 <td><a href="/wiki/Meta_Platforms" title="Meta Platforms">Meta Platforms</a>
 </td>
 <td>Technology
 </td>
 <td style="text-align:center;">164,501
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 21.9%
 </td>
 <td style="text-align:center;">74,067
 </td>
 <td><a href="/wiki/Menlo_Park,_California" title="Menlo Park, California">Menlo Park, California</a>
 </td></tr>,
 <tr>
 <td>23
 </td>
 <td><a class="mw-redirect" href="/wiki/Centene" title="Centene">Centene</a>
 </td>
 <td>Healthcare
 </td>
 <td style="text-align:center;">163,071
 </td>
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.9%
 </td>
 <td style="text-align:center;">60,500
 </td>
 <td><a href="/wiki/St._Louis" title="St. Louis">St. Louis, Missouri</a>
 </td></tr>,
 <tr>
 <td>24
 </td>
 <td><a class="mw-redirect" href="/wiki/The_Home_Depot" title="The Home Depot">The Home Depot</a>
 </td>
 <td>Retail
 </td>
 <td style="text-align:center;">159,514
 </td>

In [127]:
column_data=table.find_all('tr')

In [128]:
for row in column_data:
    row_data=row.find_all('td')
    individual_row_data=[data.text.strip() for data in row_data]
    print(individual_row_data)

[]
['1', 'Walmart', 'Retail', '680,985', '5.1%', '2,100,000', 'Bentonville, Arkansas']
['2', 'Amazon', 'Retail and cloud computing', '637,959', '11.0%', '1,556,000', 'Seattle, Washington']
['3', 'UnitedHealth Group', 'Healthcare', '400,278', '7.7%', '400,000', 'Minnetonka, Minnesota']
['4', 'Apple', 'Technology', '391,035', '2.0%', '164,000', 'Cupertino, California']
['5', 'CVS Health', 'Healthcare', '372,809', '4.2%', '259,500', 'Woonsocket, Rhode Island']
['6', 'Berkshire Hathaway', 'Conglomerate', '371,433', '1.9%', '392,400', 'Omaha, Nebraska']
['7', 'Alphabet', 'Technology and cloud computing', '350,018', '13.9%', '183,323', 'Mountain View, California']
['8', 'Exxon Mobil', 'Petroleum', '349,595', '1.5%', '60,900', 'Spring, Texas']
['9', 'McKesson Corporation', 'Healthcare', '308,951', '11.7%', '48,000', 'Irving, Texas']
['10', 'Cencora', 'Pharmacy wholesale', '293,959', '12.1%', '44,000', 'Conshohocken, Pennsylvania']
['11', 'JPMorgan Chase', 'Financials', '278,906', '16.5%', '317,233', 'New York City, New York']
['12', 'Costco Wholesale', 'Retail', '254,453', '5.0%', '333,000', 'Issaquah, Washington']
['13', 'Cigna', 'Health insurance', '247,121', '26.6%', '72,398', 'Bloomfield, Connecticut']
['14', 'Microsoft', 'Technology and cloud computing', '245,122', '15.7%', '228,000', 'Redmond, Washington']
['15', 'Cardinal Health', 'Healthcare', '226,827', '10.6%', '48,411', 'Dublin, Ohio']
['16', 'Chevron', 'Petroleum', '202,792', '0.9%', '45,298', 'Houston, Texas']
['17', 'Bank of America', 'Financials', '192,434', '11.9%', '213,193', 'Charlotte, North Carolina']
['18', 'General Motors', 'Automotive', '187,442', '9.1%', '162,000', 'Detroit, Michigan']
['19', 'Ford Motor', 'Automotive', '184,992', '5.0%', '171,000', 'Dearborn, Michigan']
['20', 'Elevance Health', 'Healthcare', '177,011', '3.3%', '103,679', 'Indianapolis, Indiana']
['21', 'Citigroup', 'Financials', '170,757', '8.9%', '227,855', 'New York City, New York']
['22', 'Meta Platforms', 'Technology', '164,501', '21.9%', '74,067', 'Menlo Park, California']
['23', 'Centene', 'Healthcare', '163,071', '5.9%', '60,500', 'St. Louis, Missouri']
['24', 'The Home Depot', 'Retail', '159,514', '4.5%', '470,100', 'Atlanta, Georgia']
['25', 'Fannie Mae', 'Financials', '152,670', '8.1%', '8,200', 'Washington, D.C.']
['26', 'Walgreens Boots Alliance', 'Pharmaceutical', '147,658', '6.2%', '252,500', 'Deerfield, Illinois']
['27', 'Kroger', 'Retail', '147,123', '-1.9%', '409,000', 'Cincinnati, Ohio']
['28', 'Phillips 66', 'Petroleum', '145,496', '-2.9%', '13,200', 'Houston, Texas']
['29', 'Marathon Petroleum', 'Petroleum', '140,412', '-6.6%', '18,300', 'Findlay, Ohio']
['30', 'Verizon Communications', 'Telecommunications', '134,788', '0.6%', '99,600', 'New York City, New York']
['31', 'Nvidia', 'Technology', '130,497', '114.2%', '36,000', 'Santa Clara, California']
['32', 'Goldman Sachs Group', 'Financials', '126,853', '17.0%', '46,500', 'New York City, New York']
['33', 'Wells Fargo', 'Financials', '125,397', '8.7%', '217,502', 'San Francisco, California']
['34', 'Valero Energy', 'Petroleum', '123,974', '-10.8%', '9,910', 'San Antonio, Texas']
['35', 'Comcast', 'Telecommunications', '123,731', '1.8%', '182,000', 'Philadelphia, Pennsylvania']
['36', 'State Farm Insurance', 'Financials', '122,951', '18.0%', '67,381', 'Bloomington, Illinois']
['37', 'AT&T', 'Conglomerate and telecommunications', '122,336', '-0.1%', '140,990', 'Dallas, Texas']
['38', 'Freddie Mac', 'Financials', '122,052', '13.0%', '8,090', 'McLean, Virginia']
['39', 'Humana', 'Health insurance', '117,761', '10.7%', '65,680', 'Louisville, Kentucky']
['40', 'Morgan Stanley', 'Financials', '107,285', '11.5%', '80,478', 'New York City, New York']
['41', 'Target', 'Retail', '106,566', '-0.8%', '440,000', 'Minneapolis, Minnesota']
['42', 'StoneX Group', 'Financials', '99,888', '64.1%', '4,500', 'New York City, New York']
['43', 'Tesla', 'Automotive and energy', '97,690', '0.9%', '125,665', 'Austin, Texas']
['44', 'Dell Technologies', 'Technology', '95,567', '8.1%', '108,000', 'Round Rock, Texas']
['45', 'PepsiCo', 'Beverage', '91,854', '0.4%', '319,000', 'Purchase, New York']
['46', 'Walt Disney', 'Media', '91,361', '2.8%', '205,040', 'Burbank, California']
['47', 'United Parcel Service', 'Transportation', '91,070', '0.1%', '372,180', 'Atlanta, Georgia']
['48', 'Johnson & Johnson', 'Pharmaceutical', '88,821', '-6.7%', '138,100', 'New Brunswick, New Jersey']
['49', 'FedEx', 'Transportation', '87,693', '-2.7%', '422,100', 'Memphis, Tennessee']
['50', 'Archer Daniels Midland', 'Food industry', '85,530', '-8.9%', '43,213', 'Chicago, Illinois']
['51', 'Procter & Gamble', 'Consumer products manufacturing', '84,039', '2.5%', '108,000', 'Cincinnati, Ohio']
['52', "Lowe's", 'Retail', '83,674', '-3.1%', '215,500', 'Mooresville, North Carolina']
['53', 'Energy Transfer Partners', 'Petroleum', '82,671', '5.2%', '16,248', 'Dallas, Texas']
['54', 'RTX', 'Aerospace and defense', '80,739', '17.1%', '186,000', 'Arlington County, Virginia']
['55', 'Albertsons', 'Retail', '79,238', '2.0%', '196,650', 'Boise, Idaho']
['56', 'Sysco', 'Food processing', '78,844', '3.3%', '76,000', 'Houston, Texas']
['57', 'Progressive', 'Insurance', '75,372', '21.4%', '66,308', 'Mayfield Village, Ohio']
['58', 'American Express', 'Financials', '74,201', '10.1%', '75,100', 'New York City, New York']
['59', 'Lockheed Martin', 'Aerospace and defense', '71,043', '5.1%', '121,000', 'Bethesda, Maryland']
['60', 'MetLife', 'Financials', '70,986', '6.1%', '45,000', 'New York City, New York']
['61', 'HCA Healthcare', 'Healthcare', '70,603', '8.7%', '271,000', 'Nashville, Tennessee']
['62', 'Prudential Financial', 'Financials', '70,405', '30.4%', '37,936', 'Newark, New Jersey']
['63', 'Boeing', 'Aerospace and defense', '66,517', '-14.5%', '172,000', 'Arlington County, Virginia']
['64', 'Caterpillar', 'Machinery', '64,809', '-3.4%', '112,900', 'Irving, Texas']
['65', 'Merck', 'Pharmaceutical industry', '64,168', '6.7%', '74,000', 'Kenilworth, New Jersey']
['66', 'Allstate', 'Insurance', '64,106', '12.3%', '55,200', 'Northfield Township, Illinois']
['67', 'Pfizer', 'Pharmaceutical industry', '63,627', '8.8%', '81,000', 'New York City, New York']
['68', 'IBM', 'Technology and cloud computing', '62,753', '1.4%', '284,500', 'Armonk, New York']
['69', 'New York Life Insurance Company', 'Insurance', '62,639', '15.3%', '15,131', 'New York City, New York']
['70', 'Delta Air Lines', 'Airline', '61,643', '6.2%', '103,000', 'Atlanta, Georgia']
['71', 'Publix Super Markets', 'Retail', '60,177', '4.6%', '255,000', 'Lakeland, Florida']
['72', 'Nationwide Mutual Insurance Company', 'Financials', '58,646', '7.4%', '22,453', 'Columbus, Ohio']
['73', 'TD Synnex', 'Information Technology', '58,452', '1.6%', '25,750', 'Clearwater, Florida']
['74', 'United Airlines Holdings', 'Airline', '57,063', '6.2%', '107,300', 'Chicago, Illinois']
['75', 'ConocoPhillips', 'Petroleum', '56,953', '-2.8%', '11,800', 'Houston, Texas']
['76', 'TJX', 'Retail', '56,360', '4.0%', '364,000', 'Framingham, Massachusetts']
['77', 'AbbVie', 'Pharmaceutical', '56,334', '3.7%', '55,000', 'Lake Bluff, Illinois']
['78', 'Enterprise Products Partners', 'Petroleum', '56,219', '13.1%', '7,800', 'Houston, Texas']
['79', 'Charter Communications', 'Telecommunications', '55,085', '0.9%', '94,500', 'Stamford, Connecticut']
['80', 'Performance Food Group', 'Food processing', '54,681', '2.5%', '36,815', 'Richmond, Virginia']
['81', 'American Airlines Group', 'Airline', '54,211', '2.7%', '133,300', 'Fort Worth, Texas']
['82', 'Capital One Financial', 'Financials', '53,938', '9.0%', '52,600', 'Tysons, Virginia']
['83', 'Cisco Systems', 'Telecom hardware manufacturing', '53,803', '-5.6%', '90,400', 'San Jose, California']
['84', 'HP', 'Technology', '53,559', '-0.3%', '58,000', 'Palo Alto, California']
['85', 'Tyson Foods', 'Food processing', '53,309', '0.8%', '138,000', 'Springdale, Arkansas']
['86', 'Intel', 'Technology', '53,101', '-2.1%', '108,900', 'Santa Clara, California']
['87', 'Oracle', 'Technology', '52,961', '6.0%', '159,000', 'Austin, Texas']
['88', 'Broadcom', 'Technology', '52,432', '46.4%', '37,000', 'Palo Alto, California']
['89', 'Deere', 'Agriculture manufacturing', '51,716', '-15.6%', '55,524', 'Moline, Illinois']
['90', 'Nike', 'Apparel', '51,361', '0.3%', '78,400', 'Beaverton, Oregon']
['91', 'Liberty Mutual Insurance Group', 'Insurance', '50,429', '-4.1%', '40,000', 'Boston, Massachusetts']
['92', 'Plains GP Holdings', 'Petroleum', '50,073', '2.8%', '4,200', 'Houston, Texas']
['93', 'USAA', 'Insurance', '48,560', '14.3%', '38,018', 'San Antonio, Texas']
['94', 'Bristol-Myers Squibb', 'Pharmaceutical', '48,300', '7.3%', '34,100', 'New York City, New York']
['95', 'Ingram Micro Holding', 'Technology', '47,984', '-0.1%', '26,125', 'Irvine, California']
['96', 'General Dynamics', 'Aerospace and defense', '47,716', '12.9%', '117,000', 'Reston, Virginia']
['97', 'Coca-Cola', 'Beverage', '47,061', '2.9%', '69,700', 'Atlanta, Georgia']
['98', 'TIAA', 'Financials', '46,946', '2.6%', '15,623', 'New York City, New York']
['99', 'Travelers', 'Insurance', '46,423', '12.2%', '34,000', 'New York City, New York']
['100', 'Eli Lilly', 'Pharmaceutical', '45,043', '32.0%', '47,000', 'Indianapolis, Indiana']

In [129]:
for row in column_data:
    row_data=row.find_all('td')
    individual_row_data=[data.text.strip() for data in row_data]
print(individual_row_data)

['100', 'Eli Lilly', 'Pharmaceutical', '45,043', '32.0%', '47,000', 'Indianapolis, Indiana']

In [130]:
column_data=table.find_all('tr')

In [132]:
for row in column_data:
    row_data=row.find_all('td')
    individual_row_data=[data.text.strip() for data in row_data]
    print(individual_row_data)
    #length=len(df)
    #df.loc[length]=individual_row_data
    #print(individual_row_data)

[]
['1', 'Walmart', 'Retail', '680,985', '5.1%', '2,100,000', 'Bentonville, Arkansas']
['2', 'Amazon', 'Retail and cloud computing', '637,959', '11.0%', '1,556,000', 'Seattle, Washington']
['3', 'UnitedHealth Group', 'Healthcare', '400,278', '7.7%', '400,000', 'Minnetonka, Minnesota']
['4', 'Apple', 'Technology', '391,035', '2.0%', '164,000', 'Cupertino, California']
['5', 'CVS Health', 'Healthcare', '372,809', '4.2%', '259,500', 'Woonsocket, Rhode Island']
['6', 'Berkshire Hathaway', 'Conglomerate', '371,433', '1.9%', '392,400', 'Omaha, Nebraska']
['7', 'Alphabet', 'Technology and cloud computing', '350,018', '13.9%', '183,323', 'Mountain View, California']
['8', 'Exxon Mobil', 'Petroleum', '349,595', '1.5%', '60,900', 'Spring, Texas']
['9', 'McKesson Corporation', 'Healthcare', '308,951', '11.7%', '48,000', 'Irving, Texas']
['10', 'Cencora', 'Pharmacy wholesale', '293,959', '12.1%', '44,000', 'Conshohocken, Pennsylvania']
['11', 'JPMorgan Chase', 'Financials', '278,906', '16.5%', '317,233', 'New York City, New York']
['12', 'Costco Wholesale', 'Retail', '254,453', '5.0%', '333,000', 'Issaquah, Washington']
['13', 'Cigna', 'Health insurance', '247,121', '26.6%', '72,398', 'Bloomfield, Connecticut']
['14', 'Microsoft', 'Technology and cloud computing', '245,122', '15.7%', '228,000', 'Redmond, Washington']
['15', 'Cardinal Health', 'Healthcare', '226,827', '10.6%', '48,411', 'Dublin, Ohio']
['16', 'Chevron', 'Petroleum', '202,792', '0.9%', '45,298', 'Houston, Texas']
['17', 'Bank of America', 'Financials', '192,434', '11.9%', '213,193', 'Charlotte, North Carolina']
['18', 'General Motors', 'Automotive', '187,442', '9.1%', '162,000', 'Detroit, Michigan']
['19', 'Ford Motor', 'Automotive', '184,992', '5.0%', '171,000', 'Dearborn, Michigan']
['20', 'Elevance Health', 'Healthcare', '177,011', '3.3%', '103,679', 'Indianapolis, Indiana']
['21', 'Citigroup', 'Financials', '170,757', '8.9%', '227,855', 'New York City, New York']
['22', 'Meta Platforms', 'Technology', '164,501', '21.9%', '74,067', 'Menlo Park, California']
['23', 'Centene', 'Healthcare', '163,071', '5.9%', '60,500', 'St. Louis, Missouri']
['24', 'The Home Depot', 'Retail', '159,514', '4.5%', '470,100', 'Atlanta, Georgia']
['25', 'Fannie Mae', 'Financials', '152,670', '8.1%', '8,200', 'Washington, D.C.']
['26', 'Walgreens Boots Alliance', 'Pharmaceutical', '147,658', '6.2%', '252,500', 'Deerfield, Illinois']
['27', 'Kroger', 'Retail', '147,123', '-1.9%', '409,000', 'Cincinnati, Ohio']
['28', 'Phillips 66', 'Petroleum', '145,496', '-2.9%', '13,200', 'Houston, Texas']
['29', 'Marathon Petroleum', 'Petroleum', '140,412', '-6.6%', '18,300', 'Findlay, Ohio']
['30', 'Verizon Communications', 'Telecommunications', '134,788', '0.6%', '99,600', 'New York City, New York']
['31', 'Nvidia', 'Technology', '130,497', '114.2%', '36,000', 'Santa Clara, California']
['32', 'Goldman Sachs Group', 'Financials', '126,853', '17.0%', '46,500', 'New York City, New York']
['33', 'Wells Fargo', 'Financials', '125,397', '8.7%', '217,502', 'San Francisco, California']
['34', 'Valero Energy', 'Petroleum', '123,974', '-10.8%', '9,910', 'San Antonio, Texas']
['35', 'Comcast', 'Telecommunications', '123,731', '1.8%', '182,000', 'Philadelphia, Pennsylvania']
['36', 'State Farm Insurance', 'Financials', '122,951', '18.0%', '67,381', 'Bloomington, Illinois']
['37', 'AT&T', 'Conglomerate and telecommunications', '122,336', '-0.1%', '140,990', 'Dallas, Texas']
['38', 'Freddie Mac', 'Financials', '122,052', '13.0%', '8,090', 'McLean, Virginia']
['39', 'Humana', 'Health insurance', '117,761', '10.7%', '65,680', 'Louisville, Kentucky']
['40', 'Morgan Stanley', 'Financials', '107,285', '11.5%', '80,478', 'New York City, New York']
['41', 'Target', 'Retail', '106,566', '-0.8%', '440,000', 'Minneapolis, Minnesota']
['42', 'StoneX Group', 'Financials', '99,888', '64.1%', '4,500', 'New York City, New York']
['43', 'Tesla', 'Automotive and energy', '97,690', '0.9%', '125,665', 'Austin, Texas']
['44', 'Dell Technologies', 'Technology', '95,567', '8.1%', '108,000', 'Round Rock, Texas']
['45', 'PepsiCo', 'Beverage', '91,854', '0.4%', '319,000', 'Purchase, New York']
['46', 'Walt Disney', 'Media', '91,361', '2.8%', '205,040', 'Burbank, California']
['47', 'United Parcel Service', 'Transportation', '91,070', '0.1%', '372,180', 'Atlanta, Georgia']
['48', 'Johnson & Johnson', 'Pharmaceutical', '88,821', '-6.7%', '138,100', 'New Brunswick, New Jersey']
['49', 'FedEx', 'Transportation', '87,693', '-2.7%', '422,100', 'Memphis, Tennessee']
['50', 'Archer Daniels Midland', 'Food industry', '85,530', '-8.9%', '43,213', 'Chicago, Illinois']
['51', 'Procter & Gamble', 'Consumer products manufacturing', '84,039', '2.5%', '108,000', 'Cincinnati, Ohio']
['52', "Lowe's", 'Retail', '83,674', '-3.1%', '215,500', 'Mooresville, North Carolina']
['53', 'Energy Transfer Partners', 'Petroleum', '82,671', '5.2%', '16,248', 'Dallas, Texas']
['54', 'RTX', 'Aerospace and defense', '80,739', '17.1%', '186,000', 'Arlington County, Virginia']
['55', 'Albertsons', 'Retail', '79,238', '2.0%', '196,650', 'Boise, Idaho']
['56', 'Sysco', 'Food processing', '78,844', '3.3%', '76,000', 'Houston, Texas']
['57', 'Progressive', 'Insurance', '75,372', '21.4%', '66,308', 'Mayfield Village, Ohio']
['58', 'American Express', 'Financials', '74,201', '10.1%', '75,100', 'New York City, New York']
['59', 'Lockheed Martin', 'Aerospace and defense', '71,043', '5.1%', '121,000', 'Bethesda, Maryland']
['60', 'MetLife', 'Financials', '70,986', '6.1%', '45,000', 'New York City, New York']
['61', 'HCA Healthcare', 'Healthcare', '70,603', '8.7%', '271,000', 'Nashville, Tennessee']
['62', 'Prudential Financial', 'Financials', '70,405', '30.4%', '37,936', 'Newark, New Jersey']
['63', 'Boeing', 'Aerospace and defense', '66,517', '-14.5%', '172,000', 'Arlington County, Virginia']
['64', 'Caterpillar', 'Machinery', '64,809', '-3.4%', '112,900', 'Irving, Texas']
['65', 'Merck', 'Pharmaceutical industry', '64,168', '6.7%', '74,000', 'Kenilworth, New Jersey']
['66', 'Allstate', 'Insurance', '64,106', '12.3%', '55,200', 'Northfield Township, Illinois']
['67', 'Pfizer', 'Pharmaceutical industry', '63,627', '8.8%', '81,000', 'New York City, New York']
['68', 'IBM', 'Technology and cloud computing', '62,753', '1.4%', '284,500', 'Armonk, New York']
['69', 'New York Life Insurance Company', 'Insurance', '62,639', '15.3%', '15,131', 'New York City, New York']
['70', 'Delta Air Lines', 'Airline', '61,643', '6.2%', '103,000', 'Atlanta, Georgia']
['71', 'Publix Super Markets', 'Retail', '60,177', '4.6%', '255,000', 'Lakeland, Florida']
['72', 'Nationwide Mutual Insurance Company', 'Financials', '58,646', '7.4%', '22,453', 'Columbus, Ohio']
['73', 'TD Synnex', 'Information Technology', '58,452', '1.6%', '25,750', 'Clearwater, Florida']
['74', 'United Airlines Holdings', 'Airline', '57,063', '6.2%', '107,300', 'Chicago, Illinois']
['75', 'ConocoPhillips', 'Petroleum', '56,953', '-2.8%', '11,800', 'Houston, Texas']
['76', 'TJX', 'Retail', '56,360', '4.0%', '364,000', 'Framingham, Massachusetts']
['77', 'AbbVie', 'Pharmaceutical', '56,334', '3.7%', '55,000', 'Lake Bluff, Illinois']
['78', 'Enterprise Products Partners', 'Petroleum', '56,219', '13.1%', '7,800', 'Houston, Texas']
['79', 'Charter Communications', 'Telecommunications', '55,085', '0.9%', '94,500', 'Stamford, Connecticut']
['80', 'Performance Food Group', 'Food processing', '54,681', '2.5%', '36,815', 'Richmond, Virginia']
['81', 'American Airlines Group', 'Airline', '54,211', '2.7%', '133,300', 'Fort Worth, Texas']
['82', 'Capital One Financial', 'Financials', '53,938', '9.0%', '52,600', 'Tysons, Virginia']
['83', 'Cisco Systems', 'Telecom hardware manufacturing', '53,803', '-5.6%', '90,400', 'San Jose, California']
['84', 'HP', 'Technology', '53,559', '-0.3%', '58,000', 'Palo Alto, California']
['85', 'Tyson Foods', 'Food processing', '53,309', '0.8%', '138,000', 'Springdale, Arkansas']
['86', 'Intel', 'Technology', '53,101', '-2.1%', '108,900', 'Santa Clara, California']
['87', 'Oracle', 'Technology', '52,961', '6.0%', '159,000', 'Austin, Texas']
['88', 'Broadcom', 'Technology', '52,432', '46.4%', '37,000', 'Palo Alto, California']
['89', 'Deere', 'Agriculture manufacturing', '51,716', '-15.6%', '55,524', 'Moline, Illinois']
['90', 'Nike', 'Apparel', '51,361', '0.3%', '78,400', 'Beaverton, Oregon']
['91', 'Liberty Mutual Insurance Group', 'Insurance', '50,429', '-4.1%', '40,000', 'Boston, Massachusetts']
['92', 'Plains GP Holdings', 'Petroleum', '50,073', '2.8%', '4,200', 'Houston, Texas']
['93', 'USAA', 'Insurance', '48,560', '14.3%', '38,018', 'San Antonio, Texas']
['94', 'Bristol-Myers Squibb', 'Pharmaceutical', '48,300', '7.3%', '34,100', 'New York City, New York']
['95', 'Ingram Micro Holding', 'Technology', '47,984', '-0.1%', '26,125', 'Irvine, California']
['96', 'General Dynamics', 'Aerospace and defense', '47,716', '12.9%', '117,000', 'Reston, Virginia']
['97', 'Coca-Cola', 'Beverage', '47,061', '2.9%', '69,700', 'Atlanta, Georgia']
['98', 'TIAA', 'Financials', '46,946', '2.6%', '15,623', 'New York City, New York']
['99', 'Travelers', 'Insurance', '46,423', '12.2%', '34,000', 'New York City, New York']
['100', 'Eli Lilly', 'Pharmaceutical', '45,043', '32.0%', '47,000', 'Indianapolis, Indiana']

In [134]:
for row in column_data[1:]:
    row_data=row.find_all('td')
    individual_row_data=[data.text.strip() for data in row_data]
    print(individual_row_data)
    #length=len(df)
    #df.loc[length]=individual_row_data
    #print(individual_row_data)

['1', 'Walmart', 'Retail', '680,985', '5.1%', '2,100,000', 'Bentonville, Arkansas']
['2', 'Amazon', 'Retail and cloud computing', '637,959', '11.0%', '1,556,000', 'Seattle, Washington']
['3', 'UnitedHealth Group', 'Healthcare', '400,278', '7.7%', '400,000', 'Minnetonka, Minnesota']
['4', 'Apple', 'Technology', '391,035', '2.0%', '164,000', 'Cupertino, California']
['5', 'CVS Health', 'Healthcare', '372,809', '4.2%', '259,500', 'Woonsocket, Rhode Island']
['6', 'Berkshire Hathaway', 'Conglomerate', '371,433', '1.9%', '392,400', 'Omaha, Nebraska']
['7', 'Alphabet', 'Technology and cloud computing', '350,018', '13.9%', '183,323', 'Mountain View, California']
['8', 'Exxon Mobil', 'Petroleum', '349,595', '1.5%', '60,900', 'Spring, Texas']
['9', 'McKesson Corporation', 'Healthcare', '308,951', '11.7%', '48,000', 'Irving, Texas']
['10', 'Cencora', 'Pharmacy wholesale', '293,959', '12.1%', '44,000', 'Conshohocken, Pennsylvania']
['11', 'JPMorgan Chase', 'Financials', '278,906', '16.5%', '317,233', 'New York City, New York']
['12', 'Costco Wholesale', 'Retail', '254,453', '5.0%', '333,000', 'Issaquah, Washington']
['13', 'Cigna', 'Health insurance', '247,121', '26.6%', '72,398', 'Bloomfield, Connecticut']
['14', 'Microsoft', 'Technology and cloud computing', '245,122', '15.7%', '228,000', 'Redmond, Washington']
['15', 'Cardinal Health', 'Healthcare', '226,827', '10.6%', '48,411', 'Dublin, Ohio']
['16', 'Chevron', 'Petroleum', '202,792', '0.9%', '45,298', 'Houston, Texas']
['17', 'Bank of America', 'Financials', '192,434', '11.9%', '213,193', 'Charlotte, North Carolina']
['18', 'General Motors', 'Automotive', '187,442', '9.1%', '162,000', 'Detroit, Michigan']
['19', 'Ford Motor', 'Automotive', '184,992', '5.0%', '171,000', 'Dearborn, Michigan']
['20', 'Elevance Health', 'Healthcare', '177,011', '3.3%', '103,679', 'Indianapolis, Indiana']
['21', 'Citigroup', 'Financials', '170,757', '8.9%', '227,855', 'New York City, New York']
['22', 'Meta Platforms', 'Technology', '164,501', '21.9%', '74,067', 'Menlo Park, California']
['23', 'Centene', 'Healthcare', '163,071', '5.9%', '60,500', 'St. Louis, Missouri']
['24', 'The Home Depot', 'Retail', '159,514', '4.5%', '470,100', 'Atlanta, Georgia']
['25', 'Fannie Mae', 'Financials', '152,670', '8.1%', '8,200', 'Washington, D.C.']
['26', 'Walgreens Boots Alliance', 'Pharmaceutical', '147,658', '6.2%', '252,500', 'Deerfield, Illinois']
['27', 'Kroger', 'Retail', '147,123', '-1.9%', '409,000', 'Cincinnati, Ohio']
['28', 'Phillips 66', 'Petroleum', '145,496', '-2.9%', '13,200', 'Houston, Texas']
['29', 'Marathon Petroleum', 'Petroleum', '140,412', '-6.6%', '18,300', 'Findlay, Ohio']
['30', 'Verizon Communications', 'Telecommunications', '134,788', '0.6%', '99,600', 'New York City, New York']
['31', 'Nvidia', 'Technology', '130,497', '114.2%', '36,000', 'Santa Clara, California']
['32', 'Goldman Sachs Group', 'Financials', '126,853', '17.0%', '46,500', 'New York City, New York']
['33', 'Wells Fargo', 'Financials', '125,397', '8.7%', '217,502', 'San Francisco, California']
['34', 'Valero Energy', 'Petroleum', '123,974', '-10.8%', '9,910', 'San Antonio, Texas']
['35', 'Comcast', 'Telecommunications', '123,731', '1.8%', '182,000', 'Philadelphia, Pennsylvania']
['36', 'State Farm Insurance', 'Financials', '122,951', '18.0%', '67,381', 'Bloomington, Illinois']
['37', 'AT&T', 'Conglomerate and telecommunications', '122,336', '-0.1%', '140,990', 'Dallas, Texas']
['38', 'Freddie Mac', 'Financials', '122,052', '13.0%', '8,090', 'McLean, Virginia']
['39', 'Humana', 'Health insurance', '117,761', '10.7%', '65,680', 'Louisville, Kentucky']
['40', 'Morgan Stanley', 'Financials', '107,285', '11.5%', '80,478', 'New York City, New York']
['41', 'Target', 'Retail', '106,566', '-0.8%', '440,000', 'Minneapolis, Minnesota']
['42', 'StoneX Group', 'Financials', '99,888', '64.1%', '4,500', 'New York City, New York']
['43', 'Tesla', 'Automotive and energy', '97,690', '0.9%', '125,665', 'Austin, Texas']
['44', 'Dell Technologies', 'Technology', '95,567', '8.1%', '108,000', 'Round Rock, Texas']
['45', 'PepsiCo', 'Beverage', '91,854', '0.4%', '319,000', 'Purchase, New York']
['46', 'Walt Disney', 'Media', '91,361', '2.8%', '205,040', 'Burbank, California']
['47', 'United Parcel Service', 'Transportation', '91,070', '0.1%', '372,180', 'Atlanta, Georgia']
['48', 'Johnson & Johnson', 'Pharmaceutical', '88,821', '-6.7%', '138,100', 'New Brunswick, New Jersey']
['49', 'FedEx', 'Transportation', '87,693', '-2.7%', '422,100', 'Memphis, Tennessee']
['50', 'Archer Daniels Midland', 'Food industry', '85,530', '-8.9%', '43,213', 'Chicago, Illinois']
['51', 'Procter & Gamble', 'Consumer products manufacturing', '84,039', '2.5%', '108,000', 'Cincinnati, Ohio']
['52', "Lowe's", 'Retail', '83,674', '-3.1%', '215,500', 'Mooresville, North Carolina']
['53', 'Energy Transfer Partners', 'Petroleum', '82,671', '5.2%', '16,248', 'Dallas, Texas']
['54', 'RTX', 'Aerospace and defense', '80,739', '17.1%', '186,000', 'Arlington County, Virginia']
['55', 'Albertsons', 'Retail', '79,238', '2.0%', '196,650', 'Boise, Idaho']
['56', 'Sysco', 'Food processing', '78,844', '3.3%', '76,000', 'Houston, Texas']
['57', 'Progressive', 'Insurance', '75,372', '21.4%', '66,308', 'Mayfield Village, Ohio']
['58', 'American Express', 'Financials', '74,201', '10.1%', '75,100', 'New York City, New York']
['59', 'Lockheed Martin', 'Aerospace and defense', '71,043', '5.1%', '121,000', 'Bethesda, Maryland']
['60', 'MetLife', 'Financials', '70,986', '6.1%', '45,000', 'New York City, New York']
['61', 'HCA Healthcare', 'Healthcare', '70,603', '8.7%', '271,000', 'Nashville, Tennessee']
['62', 'Prudential Financial', 'Financials', '70,405', '30.4%', '37,936', 'Newark, New Jersey']
['63', 'Boeing', 'Aerospace and defense', '66,517', '-14.5%', '172,000', 'Arlington County, Virginia']
['64', 'Caterpillar', 'Machinery', '64,809', '-3.4%', '112,900', 'Irving, Texas']
['65', 'Merck', 'Pharmaceutical industry', '64,168', '6.7%', '74,000', 'Kenilworth, New Jersey']
['66', 'Allstate', 'Insurance', '64,106', '12.3%', '55,200', 'Northfield Township, Illinois']
['67', 'Pfizer', 'Pharmaceutical industry', '63,627', '8.8%', '81,000', 'New York City, New York']
['68', 'IBM', 'Technology and cloud computing', '62,753', '1.4%', '284,500', 'Armonk, New York']
['69', 'New York Life Insurance Company', 'Insurance', '62,639', '15.3%', '15,131', 'New York City, New York']
['70', 'Delta Air Lines', 'Airline', '61,643', '6.2%', '103,000', 'Atlanta, Georgia']
['71', 'Publix Super Markets', 'Retail', '60,177', '4.6%', '255,000', 'Lakeland, Florida']
['72', 'Nationwide Mutual Insurance Company', 'Financials', '58,646', '7.4%', '22,453', 'Columbus, Ohio']
['73', 'TD Synnex', 'Information Technology', '58,452', '1.6%', '25,750', 'Clearwater, Florida']
['74', 'United Airlines Holdings', 'Airline', '57,063', '6.2%', '107,300', 'Chicago, Illinois']
['75', 'ConocoPhillips', 'Petroleum', '56,953', '-2.8%', '11,800', 'Houston, Texas']
['76', 'TJX', 'Retail', '56,360', '4.0%', '364,000', 'Framingham, Massachusetts']
['77', 'AbbVie', 'Pharmaceutical', '56,334', '3.7%', '55,000', 'Lake Bluff, Illinois']
['78', 'Enterprise Products Partners', 'Petroleum', '56,219', '13.1%', '7,800', 'Houston, Texas']
['79', 'Charter Communications', 'Telecommunications', '55,085', '0.9%', '94,500', 'Stamford, Connecticut']
['80', 'Performance Food Group', 'Food processing', '54,681', '2.5%', '36,815', 'Richmond, Virginia']
['81', 'American Airlines Group', 'Airline', '54,211', '2.7%', '133,300', 'Fort Worth, Texas']
['82', 'Capital One Financial', 'Financials', '53,938', '9.0%', '52,600', 'Tysons, Virginia']
['83', 'Cisco Systems', 'Telecom hardware manufacturing', '53,803', '-5.6%', '90,400', 'San Jose, California']
['84', 'HP', 'Technology', '53,559', '-0.3%', '58,000', 'Palo Alto, California']
['85', 'Tyson Foods', 'Food processing', '53,309', '0.8%', '138,000', 'Springdale, Arkansas']
['86', 'Intel', 'Technology', '53,101', '-2.1%', '108,900', 'Santa Clara, California']
['87', 'Oracle', 'Technology', '52,961', '6.0%', '159,000', 'Austin, Texas']
['88', 'Broadcom', 'Technology', '52,432', '46.4%', '37,000', 'Palo Alto, California']
['89', 'Deere', 'Agriculture manufacturing', '51,716', '-15.6%', '55,524', 'Moline, Illinois']
['90', 'Nike', 'Apparel', '51,361', '0.3%', '78,400', 'Beaverton, Oregon']
['91', 'Liberty Mutual Insurance Group', 'Insurance', '50,429', '-4.1%', '40,000', 'Boston, Massachusetts']
['92', 'Plains GP Holdings', 'Petroleum', '50,073', '2.8%', '4,200', 'Houston, Texas']
['93', 'USAA', 'Insurance', '48,560', '14.3%', '38,018', 'San Antonio, Texas']
['94', 'Bristol-Myers Squibb', 'Pharmaceutical', '48,300', '7.3%', '34,100', 'New York City, New York']
['95', 'Ingram Micro Holding', 'Technology', '47,984', '-0.1%', '26,125', 'Irvine, California']
['96', 'General Dynamics', 'Aerospace and defense', '47,716', '12.9%', '117,000', 'Reston, Virginia']
['97', 'Coca-Cola', 'Beverage', '47,061', '2.9%', '69,700', 'Atlanta, Georgia']
['98', 'TIAA', 'Financials', '46,946', '2.6%', '15,623', 'New York City, New York']
['99', 'Travelers', 'Insurance', '46,423', '12.2%', '34,000', 'New York City, New York']
['100', 'Eli Lilly', 'Pharmaceutical', '45,043', '32.0%', '47,000', 'Indianapolis, Indiana']

In [135]:
for row in column_data[1:]:
    row_data=row.find_all('td')
    individual_row_data=[data.text.strip() for data in row_data]

    length=len(df)
    df.loc[length]=individual_row_data
    #print(individual_row_data)

In [136]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [141]:
df.to_csv(r'C:\Users\PC\Documents\Web_Scraping\Companies.csv',index=False)

In [92]:
for row in table.find_all('tr'):
    cells = row.find_all('td')
    cell_text = [cell.text.strip() for cell in cells]
    if cell_text:
        data.append(cell_text)

# If you want headers from the table
headers = [th.text.strip() for th in table.find_all('th')]
df = pd.DataFrame(data, columns=headers[:len(data[0])])  # adjust header length if needed

print(df.head())

   Rank                Name                    Industry  \
0  Rank                Name                    Industry
1     1             Walmart                      Retail
2     2              Amazon  Retail and cloud computing
3     3  UnitedHealth Group                  Healthcare
4     4               Apple                  Technology

   Revenue (USD millions)  Revenue growth  Employees           Headquarters
0  Revenue (USD millions)  Revenue growth  Employees           Headquarters
1                 680,985            5.1%  2,100,000  Bentonville, Arkansas
2                 637,959           11.0%  1,556,000    Seattle, Washington
3                 400,278            7.7%    400,000  Minnetonka, Minnesota
4                 391,035            2.0%    164,000  Cupertino, California

In [93]:
# Find all headers
column_data=headers_list = soup.find_all('tr')
for h in headers_list[:10]:  # preview first 10
    print(h.text.strip())

Rank

Name

Industry

Revenue (USD millions)

Revenue growth

Employees

Headquarters
1

Walmart

Retail

680,985

  5.1%

2,100,000

Bentonville, Arkansas
2

Amazon

Retail and cloud computing

637,959

  11.0%

1,556,000

Seattle, Washington
3

UnitedHealth Group

Healthcare

400,278

  7.7%

400,000

Minnetonka, Minnesota
4

Apple

Technology

391,035

  2.0%

164,000

Cupertino, California
5

CVS Health

Healthcare

372,809

  4.2%

259,500

Woonsocket, Rhode Island
6

Berkshire Hathaway

Conglomerate

371,433

  1.9%

392,400

Omaha, Nebraska
7

Alphabet

Technology and cloud computing

350,018

  13.9%

183,323

Mountain View, California
8

Exxon Mobil

Petroleum

349,595

  1.5%

60,900

Spring, Texas
9

McKesson Corporation

Healthcare

308,951

  11.7%

48,000

Irving, Texas

In [97]:
print(f"Number of tables found: {len(tables)}")

Number of tables found: 2